"""empty message

Revision ID: ac265dae80ce
Revises: ee042f59bb99
Create Date: 2019-04-17 23:43:37.587445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac265dae80ce'
down_revision = 'ee042f59bb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('Moisture', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_Moisture'), 'data', ['Moisture'], unique=False)
    op.create_index(op.f('ix_data_humidity'), 'data', ['humidity'], unique=False)
    op.create_index(op.f('ix_data_status'), 'data', ['status'], unique=False)
    op.create_index(op.f('ix_data_temperature'), 'data', ['temperature'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_temperature'), table_name='data')
    op.drop_index(op.f('ix_data_status'), table_name='data')
    op.drop_index(op.f('ix_data_humidity'), table_name='data')
    op.drop_index(op.f('ix_data_Moisture'), table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###
